reset bucket name

diff --git a/.github/workflows/deploy-infra.yaml b/.github/workflows/deploy-infra.yaml
--- a/.github/workflows/deploy-infra.yaml
+++ b/.github/workflows/deploy-infra.yaml
@@ -28,6 +28,11 @@ jobs:
       id: create-bucket
       run: |
         BUCKET_NAME="taskman-prod-${{ secrets.AWS_ACCOUNT_ID }}"
+        if [[ ! $BUCKET_NAME =~ ^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$ ]]; then
+          echo "Error: Invalid bucket name"
+          exit 1
+        fi
+
         if aws s3 ls "s3://$BUCKET_NAME" 2>/dev/null; then
           echo "Bucket already exists"
           echo "bucket_exists=true" >> $GITHUB_OUTPUT
@@ -40,7 +45,7 @@ jobs:
     - name: Upload templates to S3
       run: |
         # Upload all templates
-        aws s3 sync ./ s3://$BUCKET_NAME/ \
+        aws s3 sync ./ s3://taskman-prod-${{ secrets.AWS_ACCOUNT_ID }}/ \
           --acl bucket-owner-full-control \
           --exclude "*" \
           --include "infra-master.yaml" \
